name: sandboxforge            # то же имя проекта!
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks: [sf_net]
    # profiles: [web]
    volumes:
      - ./web/src:/usr/share/nginx/html:ro
      - ./web/docker/nginx:/etc/nginx/conf.d:ro
networks:
  sf_net:
    external: true
