networks:
  traefik-net: {}

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"        # web
      - "443:443"      # websecure
      - "8080:8080"    # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/SandboxForge/infra/traefik/data/acme.json:/letsencrypt/acme.json
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # редирект http -> https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # ACME (http-challenge)
      - --certificatesresolvers.le.acme.email=you@example.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.sandboxforge.tech`)
      - traefik.http.routers.dashboard.service=api@internal

  api:
    image: containous/whoami
    container_name: api
    networks: [traefik-net]
    restart: unless-stopped
    labels:
    - traefik.enable=true
    - traefik.http.routers.api.rule=Host(`api.sandboxforge.tech`)
    - traefik.http.routers.api.entrypoints=websecure
    - traefik.http.routers.api.tls=true
    - traefik.http.routers.api.tls.certresolver=le
    # опционально: чтобы http тоже работал (для редиректа/челленджа)
    - traefik.http.routers.api-plain.rule=Host(`api.sandboxforge.tech`)
    - traefik.http.routers.api-plain.entrypoints=web


  casino:
    image: containous/whoami
    container_name: casino
    networks: [traefik-net]
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.casino.rule: Host(`casino.sandboxforge.tech`)
      traefik.http.routers.casino.entrypoints: websecure
      traefik.http.routers.casino.tls.certresolver: le
      traefik.http.services.casino.loadbalancer.server.port: "80"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change_me_now
    networks: [traefik-net]
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: Host(`grafana.sandboxforge.tech`)
      traefik.http.routers.grafana.entrypoints: websecure
      traefik.http.routers.grafana.tls.certresolver: le
      traefik.http.services.grafana.loadbalancer.server.port: "3000"

volumes:
  grafana-data:
