# /opt/traefik/docker-compose.yml
version: "3.9"

networks:
  traefik-net: {}

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --certificatesresolvers.le.acme.email=you@example.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/letsencrypt
    networks: [traefik-net]
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      # HTTP -> HTTPS redirect для всех хостов
      traefik.http.routers.http-catchall.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: https
      traefik.http.middlewares.redirect-https.redirectscheme.permanent: "true"

  api:
    image: containous/whoami
    container_name: api
    networks: [traefik-net]
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: Host(`api.sandboxforge.tech`)
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.tls.certresolver: le
      traefik.http.services.api.loadbalancer.server.port: "80"

  casino:
    image: containous/whoami
    container_name: casino
    networks: [traefik-net]
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.casino.rule: Host(`casino.sandboxforge.tech`)
      traefik.http.routers.casino.entrypoints: websecure
      traefik.http.routers.casino.tls.certresolver: le
      traefik.http.services.casino.loadbalancer.server.port: "80"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change_me_now
    networks: [traefik-net]
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: Host(`grafana.sandboxforge.tech`)
      traefik.http.routers.grafana.entrypoints: websecure
      traefik.http.routers.grafana.tls.certresolver: le
      traefik.http.services.grafana.loadbalancer.server.port: "3000"

volumes:
  grafana-data:
