networks:
  traefik-net:
    external: true

services:
  traefik:
    image: traefik:v3.1
    networks: [traefik-net]
    restart: unless-stopped
    ports:
      - "80:80"        # web
      - "443:443"      # websecureы
      - "8080:8080"    # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/acme.json:/letsencrypt/acme.json
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.network=traefik-net
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # редирект http -> https
      # local: disable http->https redirect
      # ACME (http-challenge)
      - --certificatesresolvers.letsencrypt.acme.email=tomlerconer777@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.sandboxforge.tech`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.tls=true
      # local: no LE resolver
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.docker.network=traefik-net

  api:
    image: containous/whoami
    networks: [traefik-net]
    restart: unless-stopped
    labels:
    - traefik.enable=true
    - traefik.docker.network=traefik-net
    - traefik.http.routers.api.rule=Host(`api.sandboxforge.tech`)
    - traefik.http.routers.api.entrypoints=web
    # local: no TLS
    # local: no LE resolver
    # опционально: чтобы http тоже работал (для редиректа/челленджа)
    - traefik.http.routers.api-plain.rule=Host(`api.sandboxforge.tech`)
    - traefik.http.routers.api-plain.entrypoints=web


  casino:
    image: containous/whoami
    networks: [traefik-net]
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-net
      traefik.http.routers.casino.rule: Host(`casino.sandboxforge.tech`)
      traefik.http.routers.casino.entrypoints: web
      # local: no TLS/LE resolver
      traefik.http.services.casino.loadbalancer.server.port: "80"
      
